# Generated by Django 5.1.1 on 2024-10-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('inscrito', 'Inscrito'), ('approved', 'Aprovado'), ('rejected', 'Rejeitdo(a)')], default='Inscrito', max_length=20),
        ),
    ]
